version: '3'

services:
  next:
    image: mm-next:latest
    build:
      context: ./frontend
    restart: always
    env_file:
      - .env.rel
    depends_on:
      - strapi
      - mysql

  nginx:
    image: mm-nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443

  strapi:
    image: mm-strapi:latest
    restart: always
    build:
      context: ./backend/strapiV4
    env_file:
      - .env.rel
    depends_on:
      - mysql
      - nginx
      - redis
      - meilisearch

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env.rel

  redis:
    image: redis:6.0-alpine
    platform: linux/x86_64
    volumes:
      - ./redis-data:/data
    env_file:
      - .env.rel

  meilisearch:
    image: getmeili/meilisearch
    command: ./meilisearch
    volumes:
      - ./meilisearch/data.ms:/data.ms
