version: '3'

services:
  next:
    image: mm-next
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - strapi
      - mysql

  nginx:
    image: mm-nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443

  strapi:
    image: mm-strapi:latest
    restart: always
    build:
      context: ./backend/strapiV4
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/strapiV4/src:/strapi/src
      - ./backend/strapiV4/config:/strapi/config
    env_file:
      - .env.dev
    depends_on:
      - mysql
      - nginx
      - redis
      - meilisearch

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - .env.dev

  redis:
    image: redis:6.0-alpine
    platform: linux/x86_64
    volumes:
      - ./redis-data:/data
    ports:
      - '6379:6379'
    env_file:
      - .env.dev

  meilisearch:
    image: getmeili/meilisearch
    command: ./meilisearch
    volumes:
      - ./meilisearch/data.ms:/data.ms
    ports:
      - "7700:7700"
